FrontEnd/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Fabric;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;

namespace FrontEnd.Pages
{
    public class IndexModel : PageModel
    {
        private readonly HttpClient httpClient;
        private readonly StatelessServiceContext serviceContext;
        private readonly FabricClient fabricClient;
        private readonly string reverseProxyBaseUri;
        private readonly Uri backEndServiceUri;
        private readonly Uri proxyAddress;

        public IndexModel(HttpClient httpClient, StatelessServiceContext serviceContext, FabricClient fabricClient)
        {
            this.httpClient = httpClient;
            this.serviceContext = serviceContext;
            this.fabricClient = fabricClient;
            reverseProxyBaseUri = Environment.GetEnvironmentVariable("ReverseProxyBaseUri");

            backEndServiceUri = new Uri($"{serviceContext.CodePackageActivationContext.ApplicationName}/BackEnd");
            proxyAddress = new Uri($"{reverseProxyBaseUri}{backEndServiceUri.AbsolutePath}");

            Values = new List<string>();
        }

        [BindProperty]
        public IEnumerable<string> Values { get; private set; }

        [BindProperty]
        public string Value { get; set; }

        public async Task OnGetAsync()
        {
            using (var response = await SendToBackEnd(async (url) => await httpClient.GetAsync(url), (part1, part2) => $"{part1}{part2}"))
            {
                Values = await response.Content.ReadAsAsync<IEnumerable<string>>();
            }
        }

        public async Task OnPostNextAsync()
        {
            await SendToBackEnd(async (url) => await httpClient.PutAsJsonAsync(url, Value), (part1, part2) => $"{part1}/{Value}{part2}");
            await OnGetAsync();
            Value = string.Empty;
        }


        public async Task OnPostBackAsync()
        {
            await OnGetAsync();
            Value = Values.Last();
            await SendToBackEnd(async (url) => await httpClient.DeleteAsync(url), (part1, part2) => $"{part1}{part2}");
            await OnGetAsync();
        }

        private async Task<HttpResponseMessage> SendToBackEnd(Func<string, Task<HttpResponseMessage>> httpMethod, Func<string, string, string> buildProxyUrl)
        {
            var partitions = await fabricClient.QueryManager.GetPartitionListAsync(backEndServiceUri);

            foreach (var partition in partitions)
            {
                var proxyUrl = buildProxyUrl($"{proxyAddress}/api/Values", $"?PartitionKey={((Int64RangePartitionInformation)partition.PartitionInformation).LowKey}&PartitionKind=Int64Range");

                var response = await httpMethod(proxyUrl);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    return response;
                }
            }
            return new HttpResponseMessage { StatusCode = System.Net.HttpStatusCode.NotFound };
        }
    }
}

FrontEnd/Pages/Index.cshtml
@page "{handler?}"
@model IndexModel
@{
    ViewData["Title"] = "Title";
}

<h1>Previous answers</h1>
<ul>
    @foreach (var value in Model.Values)
    {
        <li>@value</li>
    }
</ul>
<form method="post">
    answer: <input asp-for="Value" value="@Model.Value" />
    <button asp-page-handler="next">next</button>
    <button asp-page-handler="back">back</button>
</form>

FrontEnd/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FrontEnd</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>